# config.yml

project:
  name: "tvmov"
  description: "Genera una pagina HTML con locandine da TMDb partendo dalla lista di Vix."

api:
  tmdb:
    key: "${TMDB_API_KEY}"  # Utilizza una variabile ambientale per la chiave API
  src_urls:
    movie: "https://vixsrc.to/api/list/movie?lang=it"
    tv: "https://vixsrc.to/api/list/tv?lang=it"

html:
  output_file: "movies_miniplayers.html"
  title: "Movies & Series"
  stylesheet:
    body: 
      font-family: "Arial, sans-serif"
      background: "#000"
      color: "#fff"
      margin: 0
      padding: "20px"
    h1: 
      color: "#fff"
      text-align: "center"
      margin-bottom: "20px"
    grid:
      display: "grid"
      grid-template-columns: "repeat(auto-fill, minmax(160px, 1fr))"
      gap: "12px"
      
